### ISSUE TITLE
'yarn add gatsby-plugin-google-marketing-platform' causes an error

### ISSUE THREAD

**Issue by oobidin** [colbyfayock/gatsby-plugin-google-marketing-platform#1]
Hey!

Just tried to install this awesome plugin and got an error:

`yarn add gatsby-plugin-google-marketing-platform`
`error An unexpected error occurred: "expected hoisted manifest for \"gatsby-plugin-google-marketing-platform#gatsby#babel-preset-gatsby\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/oleg.obidin/WebstormProjects/my-project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

The yarn-error.log content is:
```
Arguments:
  /usr/local/Cellar/node/11.14.0/bin/node /usr/local/Cellar/yarn/1.15.2/libexec/bin/yarn.js add gatsby-plugin-google-marketing-platform

PATH:
  /Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/oleg.obidin/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/oleg.obidin/WebstormProjects/my-project/node_modules/.bin

Yarn version:
  1.15.2

Node version:
  11.14.0

Platform:
  darwin x64

Trace:
  Invariant Violation: expected hoisted manifest for "gatsby-plugin-google-marketing-platform#gatsby#babel-preset-gatsby"
      at invariant (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:2168:15)
      at _loop2 (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:94162:9)
      at PackageHoister.init (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:94222:7)
      at PackageLinker.getFlatHoistedTree (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:48042:20)
      at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:48053:27)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:304:30)
      at /usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:322:14
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:5228:28)
```

What do I do wrong?

**Comment by colbyfayock** [comment]
hey @oobidin sorry for the delay here, i’ve been out of town dealing with family things and just haven’t had the time to check this out.

this is a weird one i haven't seen before, can you do me a favor and try upgrading the package? gatsby was a bit out of date so i went through and upgraded all packages. im 🤞that this fixes it, but if it doesnt, i can try to dive deeper.

for the record, i tried reproducing on my personal blog after the upgrades and couldnt

**Comment by oobidin** [comment]
Hey @colbyfayock! That's weird, but it worked today :) So, thanks so much and sorry for disturbing

**Comment by colbyfayock** [comment]
@oobidin np, glad to hear it :)
