### ISSUE TITLE
custom config for analytics

### ISSUE THREAD

**Issue by herrwitzi** [colbyfayock/gatsby-plugin-google-marketing-platform#11]
Hey,
we get the following error warning in the 'Google Tag Assistant'-Plugin:
`Analytics configuration mismatch`
to fix this warning we need to include custom properties in the analytics config 
(described here: https://support.google.com/optimize/thread/7578779?hl=en)

So the config should look something like this: 
`gtag('config', 'TEST-1234', {"optimize_id":'ASDF-4321', 'linker':['myDomain.com']})`

**Comment by colbyfayock** [comment]
Closed by https://github.com/colbyfayock/gatsby-plugin-google-marketing-platform/pull/12

**Comment by herrwitzi** [comment]
Hey @colbyfayock, when can I expect a new npm release with this feature?

**Comment by colbyfayock** [comment]
just pushed out 0.1.18!
