### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by richardschulz** [colbyfayock/gatsby-plugin-google-marketing-platform#14]
yarn install _name_ is deprecated and the new command is yarn add _name_.

- [ ] Change line 24 in README.md to ```yarn add gatsby-plugin-google-marketing-platform```

Just a very minor issue, to a great plugin :)

**Comment by colbyfayock** [comment]
oops! writing it that way is a hard habit to break :P

Thanks, should be fixed now
