### ISSUE TITLE
GA Debug showing "Initializing Google Analytics." twice

### ISSUE THREAD

**Issue by elie222** [colbyfayock/gatsby-plugin-google-marketing-platform#6]
Not sure if I'm doing something wrong, but after adding this plugin, I added 2 tags in Google Tag Manger:

1. Google Analytics tag that fires on every page load
2. Google Optimize tag

Apart from that things seem to be running fine. Is this an issue? Have I done something wrong?

**Comment by colbyfayock** [comment]
can you throw your gatsby config in here? and if you have this public anywhere, thatd help me take a look as well

**Comment by elie222** [comment]
Gatsby config:

```js
module.exports = {
  siteMetadata: {
    title: `Skilled - Vetted Israeli Developers`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-favicon`,
    `gatsby-plugin-typescript`,
    {
      resolve: `gatsby-plugin-styled-components`,
      options: {
        displayName: true,
      },
    },
    {
      resolve: 'gatsby-plugin-crisp-chat',
      options: {
        // Learn about environment variables: https://gatsby.dev/env-vars
        websiteId: 'XXX',
        enableDuringDevelop: true, // Optional. Disables Crisp Chat during gatsby develop. Defaults to true.
        defer: true, // Optional. Sets the Crisp loading script to defer instead of async. Defaults to false.
        enableImprovedAccessibility: true, // Optional. Sets aria-label attribute on pop-up icon for screen readers. Defaults to true.
      },
    },
    {
      resolve: 'gatsby-plugin-i18n',
      options: {
        langKeyDefault: 'en',
        useLangKeyLayout: false,
        prefixDefault: false,
      },
    },
    {
      resolve: 'gatsby-plugin-google-marketing-platform',
      options: {
        dataLayer: {
          // Preset dataLayer values
          gaPropertyId: 'UA-149xx',
        },
        tagmanager: {
          id: 'GTM-NPxx',
          params: {
            // GTM URL Parameters
            // Ex: https://www.googletagmanager.com/gtm.js?id=[ID]&gtm_cookies_win=x
            // gtm_cookies_win: 'x'
          }
        },
        analytics: {
          id: 'UA-149xx',
        },
        optimize: {
          id: 'GTM-5Rxx',
        },
        includeInDevelopment: false,
      },
    }
  ],
}
```

**Comment by elie222** [comment]
The two tags I'm using:
![image](https://user-images.githubusercontent.com/3090527/67055724-dafa6a00-f151-11e9-8390-8ae81ec5fe79.png)

I tried disabling them, but then no events showed.

**Comment by colbyfayock** [comment]
so i just set it up on mine to test this and i think what you're seeing is expected. the reason being, Optimize works along side GA, so when that loads, I think thats why you see the second instance.

![image](https://user-images.githubusercontent.com/1045274/67056918-4f1a1b00-f11c-11e9-8735-bde199dd6528.png)

![image](https://user-images.githubusercontent.com/1045274/67057224-a4a2f780-f11d-11e9-9a82-c279fffe73f6.png)

my guess without being able to see much about the output is that when Google Optimize loads, its showing as a second initialization. can you show me where you see that? 

do you have the Google Tag Assistant extension? if you take a look at that, it will let you know if it's properly installed. for instance, on my website:

![image](https://user-images.githubusercontent.com/1045274/67057711-b1c0e600-f11f-11e9-9e21-8d0954ad66ee.png)

The blue means it's a nonstandard implementation, but thats just beacuse it doesn't use the basic default and utilizes tag manager instead.

**Comment by elie222** [comment]
Yeah, seems to be okay. I get these warnings, but should be able to address them on my end.
![image](https://user-images.githubusercontent.com/3090527/67574006-493ac000-f742-11e9-8c1f-725e9e911116.png)
