### ISSUE TITLE
Google Optimize Diagnostic Warning

### ISSUE THREAD

**Issue by msaglietto** [colbyfayock/gatsby-plugin-google-marketing-platform#9]
Hey.. thanks for the plugin it save me some work to just add the plugin but I get the followings warning by the google optimize diagnostic:

```
We found problems with the Optimize installation on this page
Refer to the diagnostics below to fix problems and troubleshoot any issues with your installation. Learn more about diagnostics .
Warnings
The anti-flicker snippet timed out
The anti-flicker snippet might not have been configured correctly or the timeout value is too short. The anti-flicker timeout is a worst-case scenario. Your page will only be hidden for the full timeout if the experiment cannot execute sooner (and when it does, the page is unhidden immediately). When anti-flicker times out, your experiment doesn't run on that page load, which can limit the efficacy of your experiment and results. Regardless of timeout value, ensure that the Optimize plugin is deployed correctly and not late in the page (e.g. in the <BODY>).

Anti-flicker snippet configuration error
The Optimize container is loaded via Google Tag Manager. The anti-flicker snippet should be configured to use the Tag Manager container ID (GTM-XXX), not the Optimize container ID (GTM-YYY). While this won't cause a problem when always firing the Optimize tag, it can adversely affect your site performance when you stop firing it, or if you fire it conditionally. In this case the best practice is to use the Tag Manager container ID in the anti-flicker snippet.

Suggestions
Anti-flicker snippet timed out too fast
The anti-flicker snippet timeout value is too short. When anti-flicker times out your experiment doesn't run, decreasing the amount of visitors that will see it. The anti-flicker timeout value is designed as a worst case scenario, not the actual time that your page will be hidden.
```

It seems you have to use the tag manager id in the antiflicker .. 
Also an option for the anti flicker timeout could be added .. what do you think?
Its this something would you like to address in your plugin ?

**Comment by colbyfayock** [comment]
@msaglietto it _should_ be using the ID in the snippet, I'd be curious to see what your output looks like, can you share the source and the compiled code?

Here's showing where the ID is added:
https://github.com/colbyfayock/gatsby-plugin-google-marketing-platform/blob/master/src/lib/optimize.js#L33

I think you can also specify a custom timeout already too. in your optimize object, you can set it as a property. i should probably document this :)

```
optimize: {
    id: 'ASDF-4321',
    timeout: 100
}
```

Want to give that a shot?

**Comment by colbyfayock** [comment]
oh I think I see what you're saying about the anti-flicker snippet, sorry I misread. thats interesting. i think that's a great point, i can update that or if you'd like to make a pull request feel free!

**Comment by msaglietto** [comment]
Sorry I should have made the PR thanks @colbyfayock

**Comment by colbyfayock** [comment]
@msaglietto np :) @herrwitzi grabbed it, just waiting for a quick test fix and we'll get that in

**Comment by colbyfayock** [comment]
hey @msaglietto just merged and published to npm, version 0.1.16, can you pull it down when you have a moment and give it a shot?

**Comment by msaglietto** [comment]
Thanks you guys .. beside a couple of timeout that I can configure now the diagnostic say its all fine now !!

**Comment by msaglietto** [comment]
A side question have you made it so the experiment triggers on client navigation? because right now for me the experiment works only on full page reload

**Comment by colbyfayock** [comment]
Good question, didn't consider that. Would need to add an activation event: https://support.google.com/optimize/answer/7008840?hl=en - the question is where in Gatsby can I hook into that.  I can try to look into this

**Comment by msaglietto** [comment]
Yes I tried sending the activation event but I could not make it work with my experiment ... also I was thinking where in Gatsby you could hook that like a post navigation event or something

**Comment by colbyfayock** [comment]
yeah - so the only issue with hooking directly into a gatsby event is that from what i understand, the only event they would fire on would be the page change, particularly we could use `onRouteUpdate` in the browser API, however, that probably won't work for instances where you interact with add/remove from the dom within the page, like if you have tabs or something.

the MutationObserver API is an option, seems like it might be the best option at this point, im just concerned about adding the performance overhead for all installs, though Gatsby sites probably don't really work without it. my thinking here is to subscribe to changes in the entire dom tree, so thinking along the lines of:
```
function callback() {
  dataLayer.push({'event': 'optimize.activate'}); 
}
const observer = new MutationObserver(callback);
observer.observe(document.body, {
  attributes: true,
  childList: true,
  characterData: true,
  attributeFilter: ['style']
});
```
thinking can add that with the plugin somewhere, maybe just next to the rest of the datalayer code 🤔

thoughts?

**Comment by colbyfayock** [comment]
here's what I'm thinking 🤔https://github.com/colbyfayock/gatsby-plugin-google-marketing-platform/pull/13

**Comment by colbyfayock** [comment]
@msaglietto any thoughts on this before i give it a shot?

**Comment by msaglietto** [comment]
@colbyfayock I think the idea is good but having the MutationObserver on the body could trigger too much activation .. I dont know what kind of overhead that could bring to the page but it sounds like to many unnecessary activation 
If react router is using history maybe https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event or https://developer.mozilla.org/es/docs/Web/API/WindowEventHandlers/onhashchange for hash (dont know if you can say to gatsby that you want to use hash) ?

**Comment by colbyfayock** [comment]
i dont mind the popstate event, i can look into that. the issue with utilizing only a history API though is I think you'll miss out on DOM changes between those page changes, such as tabs changing.

ill perf out the mutation observer API, maybe i can set it up to be opt-in with configuration. i dont believe there would be a ton of overhead from it, the extra activations wouldn't necessarily "hurt" anything aside from the function call itself, but either way, opting in would prevent any of those concerns.

so maybe something like:
```
optimize: {
  id: 'ASDF-4321',
  activateOn: '[history|observer|false]'
},
```

**Comment by msaglietto** [comment]
Yes sounds good to have the options so we can try and see what works best

**Comment by colbyfayock** [comment]
okay - I created a new PR because i accidentally rewrote it 🤦‍♂ anyways https://github.com/colbyfayock/gatsby-plugin-google-marketing-platform/pull/15

i added an `activateOn` option like i mentioned above, currently only supports `observer`. i went to add `history` as well but the `popstate` didn't seem to work as i needed it to by default:
```
{ this.activateOn === 'history' && (
  <script
    key={`${COMPONENT_KEY}-activation-observer-history`}
    dangerouslySetInnerHTML={{
      __html: stripIndent`
        (function () {
          function activateOptimize() {
            console.log('pop')
            dataLayer.push({
              'event': 'optimize.activate'
            });
          }
          window.onpopstate = activateOptimize;
        })();
      `,
    }}
  />
) }
```
it didn't seem to work when navigating with Gatsby's `Link` component, however, when I just put `#test` in the url to navigate to a hash with the browser itself, it seemed to work. i would need to look up more about how to make this work or figure out how we can attach a listener. maybe i can wrap the app with something to listen to the history 🤔

**Comment by colbyfayock** [comment]
@msaglietto im gonna close this issue since we're away from the original intent of the thread, feel free to open a new issue if there's more you want me to look at or have another idea for the activation work. curious also if you get a chance to try the observer option i added in!

**Comment by msaglietto** [comment]
@colbyfayock Happy new year !!

Yes you are right this ticket can be closes since you already address it thanks you ..

Early this week I give it a try to master version (it took me a while to realize I have to build it first =P) and I wanted to make some more test that I will do today ...

With the observer activation I can see two activate events on every time I navigate the page ... but the problem reside on when the experiment is active for example if you modify asd.com/test you have to make sure to include asd.com on your experiment setup ... so maybe that was the problem and not the activation I will let you know if I can figure it out ... thanks!!

**Comment by colbyfayock** [comment]
Happy new year! sorry haven't had much time to poke at this, but please open another issue if you find there still is a problem. won't be available for the next 2 weeks but should be able to work through any issues after that :)
